Updated shell scripts to be more agreeable to non-Mac OS

diff --git a/bin/flashrom_dump b/bin/flashrom_dump
--- a/bin/flashrom_dump
+++ b/bin/flashrom_dump
@@ -1,7 +1,11 @@
 #!/usr/bin/env sh
 set -e  # exit immediately if any command fails
 set -u  # unset variables are errors
-set -o pipefail  # pipeline fails if any command fails
+if uname -o | grep "Darwin"
+then
+  set -o pipefail  # pipeline fails if any command fails
+
+fi
 #set -x # show everything
 
 # Reads a SPI flash ROM on Mac
@@ -20,7 +24,10 @@ then
   exit 1
 fi
 
-SPISPEED=5M
+if [ ! -n "${var:+set}" ]
+then
+  SPISPEED=5M
+fi
 
 if [ -z "${FLASHROM_ARGS+x}" ]
 then
@@ -48,4 +55,3 @@ else
   echo "Bad read, try again."
   rm ${FILENAME} ${VERIFICATION_FILENAME}
 fi
-
diff --git a/bin/serprog_dev b/bin/serprog_dev
--- a/bin/serprog_dev
+++ b/bin/serprog_dev
@@ -1,7 +1,11 @@
 #!/usr/bin/env sh
 set -e  # exit immediately if any command fails
 set -u  # unset variables are errors
-set -o pipefail  # pipeline fails if any command fails
+if uname -o | grep "Darwin"
+then
+  set -o pipefail  # pipeline fails if any command fails
+
+fi
 #set -x # show everything
 
 # Outputs the path of the device that is a Pico serprog
diff --git a/bin/test/test_setup_env b/bin/test/test_setup_env
--- a/bin/test/test_setup_env
+++ b/bin/test/test_setup_env
@@ -3,7 +3,11 @@
 # Test setup_env
 set -e  # exit immediately if any command fails
 set -u  # unset variables are errors
-set -o pipefail  # pipeline fails if any command fails
+if uname -o | grep "Darwin"
+then
+  set -o pipefail  # pipeline fails if any command fails
+
+fi
 set -x # show everything
 
 GIT_DIR=$(git rev-parse --show-toplevel)
